### PR TITLE
Add basic LZ4 Frame v1.5.0 support

### PR DESCRIPTION
**Pull request by drcrallen**
This PR is to add support for most of the features of Frames 1.5.0 as found at https://docs.google.com/document/d/1cl8N1bmkTdIpPLtnlzbBSFAdUeyNo5fwfHbHU7VRNWY

This is a port of some [Kafka code](https://raw.githubusercontent.com/apache/kafka/trunk/clients/src/main/java/org/apache/kafka/common/record/ByteBufferOutputStream.java)

This is technically ASF Apache license 2.0 code.

### CODE REVIEW

**Comment by jpountz** [comment]
Thanks! I only skimmed through the patch but it looks great.

**Comment by jpountz** [comment]
Out of curiosity, do you know if the Kafka people are aware of your efforts to contribute this framing format support upstream?

**Comment by drcrallen** [comment]
@jpountz Yes and no. I let the original contributor know about the patch and where to find it. But I do not have the capacity to test rolling upgrades from the prior version to this version, so I cannot immediately suggest a backport of the code to the main branch. I'm also only tangentially familiar with the way that the prior version was used in kafka in the wild.

**Comment by drcrallen** [comment]
There are still a few potential issues with this PR: like the lack of capacity to specify the compressor and decompressor. But I wasn't sure what your preferred way of handling it would be.

**Comment by ederrf** [comment]
Hi @jpountz, I started using today the code provided by @drcrallen, and for my needs, it is working as expected. I'll be running more tests along the following days. Are you planning on merging this PR anytime soon ?

**Comment by jeroenvuurens** [comment]
Thanks for providing an extension. I've also started using the code provided here, it works, and the output is compatible with the unix command line lz4 util.

**Comment by hochgi** [comment]
:+1: for merging this PR

**Comment by drcrallen** [comment]
@jpountz anything in particular you would like to see here before merging?

**Comment by jjhart** [comment]
@drcrallen - I just made a couple comments on the pull request that might explain jpountz's hesitancy to merge this PR (not to put words in his mouth, I have no idea.  I just know they were problematic when I tried to test this PR on my machine).

**Comment by drcrallen** [comment]
for what its worth I fixed the mentioned items. Still not sure the best way to handle the change in https://github.com/Cyan4973/lz4/commit/f02adc79389732177dca6fa21a3e716249aa63dd since there's not a multiple-version-friendly flag

**Comment by FergusNelson** [comment]
I've used the LZ4FrameInputStream code to process some large (~150GB) files and can confirm that it worked very well.

**Comment by ScalaWilliam** [comment]
Would be very useful to have this. I was lost as to why I couldn't decompress a file I compressed with the reference implementation.

**Comment by odaira** [comment]
Thanks for the contribution!

I found a few problems, so I'll fix them in the next commit. I'll also revise the coding style and will add a license note.

**Comment by odaira** [comment]
@drcrallen Is there any reason LZ4FrameOutputStream.FrameInfo is a public class?  As far as I read the code, it is used only internally in LZ4FrameOutputStream and LZ4FrameInputStream.

**Comment by ScalaWilliam** [comment]
Excellent!

**Pull request merged**
