### PR TITLE
enable aarch64 support for lz4-java

### PR DESCRIPTION
**Pull request by rockyzhang**
This patch enables the lz4-java support for aarch64 architecture it would

1) enables the 64bit access for lz4 native lib embedded in lz4-java
2) adds the JNI native objects which has been build

Signed-off-by: Rocky Zhang rocky.zhang@linaro.org

### CODE REVIEW

**Comment by yuqilinaro** [comment]
Is this patch ok to be merged for support for AArch64?
Could you please review it?  thanks a lot!

**Comment by yuqilinaro** [comment]
Hi @jpountz ,

Could you please give some comments for this?

BRs
Yuqi

**Comment by guyuqi** [comment]
@Cyan4973  Is there any obstacle to merge this PR?  I've verified it on AArch64

**Comment by Cyan4973** [comment]
I don't have any reason to think there is any problem, but I shouldn't be the one to judge it.
I'm in the process of selecting the new maintainer of lz4-java.
He will have the charge to review this PR.

**Comment by guyuqi** [comment]
@Cyan4973,  Really thanks for your quick response. I'm looking forward to getting any feedback for this patch from the new lz4-java maintainer.

**Comment by odaira** [comment]
Thanks much for your contribution!

**Pull request merged**
